import type { Metadata } from "next";
import "./globals.css";
import NextThemeProviders from "./context/NextThemeProvider";
import NavBar from "./components/navbar/Navbar";
import Footer from "./components/home/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <NextThemeProviders>
          {" "}
          <header>
            <NavBar />
          </header>
          {children}
          <footer>
            <Footer />
          </footer>
        </NextThemeProviders>
      </body>
    </html>
  );
}
